### ISSUE TITLE
Problem with EventStoreDownloadMojo.java unTarGz method ??? 

### ISSUE THREAD

**Issue by hackerwin7** [fuinorg/event-store-maven-plugin#17] opened 2016-12-17 06:34 UTC
**FileNotFoundException** with this case:
if [line 242](https://github.com/fuinorg/event-store-maven-plugin/blob/master/es-maven-plugin/src/main/java/org/fuin/esmp/EventStoreDownloadMojo.java#L242)  get the **first entry** such as xxx/lib/xxx.jar (is not directory) and the directory lib have not creates then [line 250](https://github.com/fuinorg/event-store-maven-plugin/blob/master/es-maven-plugin/src/main/java/org/fuin/esmp/EventStoreDownloadMojo.java#L250) will throw FileNotFoundException

**Comment by michael-schnell** [comment] 2016-12-17 08:10
Hey,

Can you provide an example for a download that fails? What version did you try? Or just add an example tar file that cannot be unpacked to this isse. Thx!

Cheers,
Michael

**Comment by hackerwin7** [comment] 2016-12-19 07:05
Hi,

I just put a normal tar.gz package file to test the unTarGz method, I debug the method with the example file and find the issue.

For example:
the content of example.tar.gz:
* bin
    * bin/some.sh
    * ......
* conf
    * ........ (some config files)
* lib
    * (some jar files)
* others (other directories like above)

When I debug the **unTarGz(new File(arhive file path), new File(/home/userName))** method, the **tarIn.getNextEntry()** get the first entry's name is example/lib/example.jar, while the directory example/lib have not created, the **entry.isDirectory()** is false, so the method don't move into **createIfNecessary(file)** to create some necessary directories. 
I think the tarIn.getNextEntry() sequence of content is {example/, example/lib, example/lib/xxx.jar, ....} which is okay.
While the sequence of content is {example/lib/xxx.jar, ....} which will throw exception and the example/lib have not created.

Version info:
apache: commons-compress: 1.12

**Comment by michael-schnell** [comment] 2016-12-23 09:14
Hi,

I added two new tests for unzip and untargz according to your description:
https://github.com/fuinorg/event-store-maven-plugin/blob/master/es-maven-plugin/src/test/java/org/fuin/esmp/EventStoreDownloadMojoTest.java

It unpacks the two files:
https://github.com/fuinorg/event-store-maven-plugin/blob/master/es-maven-plugin/src/test/resources/example.tar.gz
https://github.com/fuinorg/event-store-maven-plugin/blob/master/es-maven-plugin/src/test/resources/example.zip

Unfortunately I cannot reproduce your problem. It works fine in the test.

Maybe you can provide the original example file?

Cheers,
Michael

**Comment by hackerwin7** [comment] 2016-12-26 03:08
Hi,

Thanks your response, I test the sample, it is okay for your example.tar.gz but my TarGz file is not. I find the problem is the file UnTarGz sequence.

Your file sequence is:
bin/
bin/xx
lib/
lib/xxx

But my file sequence is:
lib/xxx.jar
.....

there is original file you can test it:
[mars-admin-1.0-SNAPSHOT.tar.gz](https://github.com/fuinorg/event-store-maven-plugin/files/672483/mars-admin-1.0-SNAPSHOT.tar.gz)


Thanks.

**Comment by hackerwin7** [comment] 2016-12-26 03:12
I use tar tvf command to compare the two files sequence below:

your:
> drwxrwxr-x michi/michi       0 2016-12-23 16:29 bin/
> -rwxrwxr-x michi/michi      23 2016-12-23 16:30 bin/some.sh
> drwxrwxr-x michi/michi       0 2016-12-23 16:31 conf/
> -rw-rw-r-- michi/michi      27 2016-12-23 16:31 conf/test.xml
> drwxrwxr-x michi/michi       0 2016-12-23 16:33 lib/
> -rw-rw-r-- michi/michi  284220 2011-12-29 21:21 lib/commons-lang-2.6.jar
> -rw-rw-r-- michi/michi  208700 2016-07-14 01:10 lib/commons-io-2.5.jar


my:
> -rw-rw-r-- fff/fff      128933 2016-12-22 17:34 mars-admin-1.0-SNAPSHOT/lib/mars-admin-1.0-SNAPSHOT.jar
> -rw-rw-r-- fff/fff      133531 2016-04-20 11:21 mars-admin-1.0-SNAPSHOT/lib/log4j-api-2.1.jar
> -rw-rw-r-- fff/fff       22542 2016-04-20 11:21 mars-admin-1.0-SNAPSHOT/lib/log4j-slf4j-impl-2.1.jar
> -rw-rw-r-- fff/fff       29257 2016-04-20 11:21 mars-admin-1.0-SNAPSHOT/lib/slf4j-api-1.7.7.jar
> -rw-rw-r-- fff/fff      824749 2016-04-20 11:21 mars-admin-1.0-SNAPSHOT/lib/log4j-core-2.1.jar
> -rw-rw-r-- fff/fff       20647 2016-04-20 11:21 mars-admin-1.0-SNAPSHOT/lib/log4j-over-slf4j-1.6.6.jar
> -rw-rw-r-- fff/fff      270553 2015-12-21 18:45 mars-admin-1.0-SNAPSHOT/lib/snakeyaml-1.11.jar
> -rw-rw-r-- fff/fff       16046 2016-04-20 11:20 mars-admin-1.0-SNAPSHOT/lib/json-simple-1.1.jar
> -rw-rw-r-- fff/fff      720931 2016-05-26 16:59 mars-admin-1.0-SNAPSHOT/lib/httpclient-4.4.1.jar
> -rw-rw-r-- fff/fff      322234 2016-05-26 16:59 mars-admin-1.0-SNAPSHOT/lib/httpcore-4.4.1.jar
> -rw-rw-r-- fff/fff       61829 2015-12-23 10:01 mars-admin-1.0-SNAPSHOT/lib/commons-logging-1.2.jar
> -rw-rw-r-- fff/fff      263965 2015-12-21 10:31 mars-admin-1.0-SNAPSHOT/lib/commons-codec-1.9.jar
> -rw-rw-r-- fff/fff      341323 2016-10-10 14:27 mars-admin-1.0-SNAPSHOT/lib/sigar-1.7.0-v20131027.jar
> -rw-rw-r-- fff/fff      284220 2015-12-21 18:45 mars-admin-1.0-SNAPSHOT/lib/commons-lang-2.6.jar
> -rw-rw-r-- fff/fff       52543 2016-09-01 11:12 mars-admin-1.0-SNAPSHOT/lib/commons-exec-1.1.jar
> -rw-rw-r-- fff/fff      111908 2016-09-01 11:12 mars-admin-1.0-SNAPSHOT/lib/metrics-core-3.1.0.jar
> -rw-rw-r-- fff/fff       79474 2016-09-01 11:12 mars-admin-1.0-SNAPSHOT/lib/disruptor-3.3.2.jar
> -rw-rw-r-- fff/fff      185140 2015-12-21 10:31 mars-admin-1.0-SNAPSHOT/lib/commons-io-2.4.jar
> -rw-r--r-- fff/fff        1559 2016-12-22 16:18 mars-admin-1.0-SNAPSHOT/conf/mars-admin.yaml
> -rw-r--r-- fff/fff        2586 2016-12-02 18:43 mars-admin-1.0-SNAPSHOT/conf/mars-admin-log4j2.xml
> -rwxr-xr-x fff/fff        2401 2016-12-12 15:40 mars-admin-1.0-SNAPSHOT/bin/mars-admin
> -rwxr-xr-x fff/fff       11568 2016-12-12 15:43 mars-admin-1.0-SNAPSHOT/bin/mars-admin.py
> -rwxr-xr-x fff/fff         347 2016-12-07 11:31 mars-admin-1.0-SNAPSHOT/bin/mars-admin.sh
> drwxrwxrwx fff/fff           0 2016-10-10 14:24 mars-admin-1.0-SNAPSHOT/native/
> -rw-r--r-- fff/fff      414184 2016-10-10 14:24 mars-admin-1.0-SNAPSHOT/native/libsigar-universal64-macosx.dylib
> -rw-r--r-- fff/fff      402432 2016-10-10 14:24 mars-admin-1.0-SNAPSHOT/native/sigar-amd64-winnt.dll
> -rw-r--r-- fff/fff       99584 2016-10-10 14:24 mars-admin-1.0-SNAPSHOT/native/sigar-x86-winnt.lib
> -rw-r--r-- fff/fff      233385 2016-10-10 14:24 mars-admin-1.0-SNAPSHOT/native/libsigar-x86-linux.so
> -rw-r--r-- fff/fff      377668 2016-10-10 14:24 mars-admin-1.0-SNAPSHOT/native/libsigar-universal-macosx.dylib
> -rw-r--r-- fff/fff      266240 2016-10-10 14:24 mars-admin-1.0-SNAPSHOT/native/sigar-x86-winnt.dll
> -rw-r--r-- fff/fff      246605 2016-10-10 14:24 mars-admin-1.0-SNAPSHOT/native/libsigar-amd64-linux.so

**Comment by michael-schnell** [comment] 2016-12-26 08:04
Hi,

OK, I wasn't aware that it's possible just to add the files (without directories).

Should be fixed now.

Cheers,
Michael

**Closed as completed** 2016-12-26 08:03 UTC
